development:
  adapter: mysql2
  database: timecard_dev
  host: localhost
  username: mysqluser
  password: mysqlpass

production:
  adapter: mysql2
  database: timecard_prod
  host: localhost
  username: mysqluser
  password: mysqlpass

test:
  adapter: mysql2
  database: timecard_test
  host: localhost
  username: mysqluser
  password: mysqlpass
